stages:
  - build
  - deploy
build-and-push:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"

staging:
  stage: deploy
  image:
    name: curlimages/curl:latest
  script:
  - "curl -X POST --fail -F token=TOKEN -F ref=REF_NAME https://gitlab.science.upjs.sk/api/v4/projects/738/trigger/pipeline"
